mplcpp:
	- g++-9 draw_kernels.cpp -std=gnu++14 -Wall -I /Users/tp5/code/gravitas/external -I ../src/ -I /System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I /usr/local/lib/python2.7/site-packages/numpy/core/include -L /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/config -lpython2.7 -g -O0

clean:
	- rm *.out
